# Generated by Django 2.1.5 on 2019-01-15 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host_process',
            old_name='process_cup',
            new_name='process_cpu',
        ),
    ]
