# Generated by Django 2.1.5 on 2019-01-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190115_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_process',
            name='process_in_host',
            field=models.ForeignKey(default=1, on_delete='CASCADE', to='app01.Host_List'),
        ),
    ]
