# Generated by Django 2.1.5 on 2019-01-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190115_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_list',
            name='nid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='host_process',
            name='process_in_host',
            field=models.ForeignKey(default=1, on_delete='CASCADE', to='app01.Host_List'),
        ),
    ]
