# Generated by Django 2.1.5 on 2019-01-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('user_pwd', models.CharField(max_length=64)),
                ('user_tel', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=40)),
            ],
        ),
    ]
