# Generated by Django 2.1.5 on 2019-01-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_gender',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
