# Generated by Django 2.1.5 on 2019-01-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_userinfo_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('capthion', models.CharField(max_length=32)),
            ],
        ),
    ]
