# Generated by Django 2.1.5 on 2019-01-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_usergroup_ctime'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='uptime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
