# Generated by Django 2.1.5 on 2019-01-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_usergroup_user_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='user_type_id',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_group',
            field=models.ForeignKey(default=1, on_delete='CASCADE', to='cmdb.UserGroup'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='capthion',
            field=models.CharField(help_text='数字字母下划线', max_length=32),
        ),
    ]
